$(document).ready(function(){

  window.sr = ScrollReveal();
  sr.reveal('#banner-heading',{
    origin:'bottom',
    duration:2000,
    distance:'200px'
  });
  sr.reveal('#author-img',{
    viewFactor: 0.2,
    origin:'left',
    duration:1000,
    distance:'100px',
    delay:500
  });
  sr.reveal('#author-content',{
    origin:'right',
    duration:1500,
    distance:'100px',
    delay:500
  });
  sr.reveal('#experience-head',{
    origin:'top',
    duration:1500,
    distance:'300px',
    viewFactor:0.2
  });
  sr.reveal('#awards-head',{
    origin:'left',
    duration:1500,
    distance:'600px',
    viewFactor:0.2
  });
  sr.reveal('#grant-head',{
    origin:'bottom',
    duration:1500,
    distance:'400px',
    viewFactor:0.2
  });
  sr.reveal('.grantContentLeft',{
    origin:'left',
    duration:1000,
    distance:'400px',
    viewFactor:0.2
  });
  sr.reveal('.grantContentRight',{
    origin:'right',
    duration:1000,
    delay:500,
    distance:'400px',
    viewFactor:0.2
  });

  //teaching
  sr.reveal('#teaching-head',{
    origin:'top',
    duration:1000,
    distance:'400px',
    viewFactor:0.2
  });
  sr.reveal('#pro-head',{
    origin:'top',
    duration:1200,
    distance:'400px'
  });
  sr.reveal('.serLeft',{
    origin:'left',
    duration:1300,
    distance:'400px',
    viewFactor:0.2
  });
  sr.reveal('.teachingCenter',{
    origin:'bottom',
    duration:1000,
    distance:'400px',
    viewFactor:0.2
  });
  sr.reveal('.teachingLeft',{
    origin:'left',
    duration:1200,
    delay:200,
    distance:'400px',
    viewFactor:0.2
  });
  sr.reveal('.teachingRight',{
    origin:'right',
    duration:1200,
    delay:400,
    distance:'400px',
    viewFactor:0.2
  });
})